export const mockedEdnResponse = `[:ok 
		{:query/rows
			[
				{:order/type					 :order.type/barcodes,
				:order/reference         	      "183204287007",
				:order/date            		  	 "1/10/2018",
				:order/status					"processed",
				:order/invoice-download			"https://www.dropbox.com/s/v6lgrhheu8rqdx5/invoice-barcodes.pdf?dl=1",
				:order/package-download 		"https://www.dropbox.com/s/ugq6zxuer7kmrl1/package-barcodes.zip?dl=1",
				:order/barcodes  				 [111111]
				:order/owner-email            	 "bruce.wayne@batcave.com",
				:order/customer-address-street	 "42 Wayne Street, Gotham",
				:order/quantity              	  1,
				:order/product-code          	  "Codigo de barras",
				:order/amount                	  "10.00M",
				:order/customer-name          	 "Bruce Wayne",
				:order/customer-phone         	 "0721234567",
				:order/customer-address-zip   	 "71939540",
				:order/owner-name             	 "Wayne Enterprises",
				:order/address-state          	 "DF",
				:order/customer-address-city  	 "Brasilia",
				:order/customer-tax-id       	  "95414332191"}

				{:order/type					 :order.type/barcodes,
				:order/reference         	      "283204287007",
				:order/date            		  	 "2/10/2018",
				:order/status					"completed",
				:order/invoice-download			"https://www.dropbox.com/s/v6lgrhheu8rqdx5/invoice-barcodes.pdf?dl=1",
				:order/package-download 		"https://www.dropbox.com/s/ugq6zxuer7kmrl1/package-barcodes.zip?dl=1",
				:order/barcodes  				 [111111 222222]
				:order/owner-email            	 "bruce.wayne@batcave.com",
				:order/customer-address-street	 "42 Wayne Street, Gotham",
				:order/quantity              	  2,
				:order/product-code          	  "Codigo de barras",
				:order/amount                	  "20.00M",
				:order/customer-name          	 "Bruce Wayne",
				:order/customer-phone         	 "0721234567",
				:order/customer-address-zip   	 "71939540",
				:order/owner-name             	 "Wayne Enterprises",
				:order/address-state          	 "DF",
				:order/customer-address-city  	 "Brasilia",
				:order/customer-tax-id       	  "95414332191"}

				{:order/type					 :order.type/barcodes,
					:order/reference         	      "683204287007",
					:order/date            		  	 "6/10/2018",
					:order/status					"processed",
					:order/invoice-download			"https://www.dropbox.com/s/v6lgrhheu8rqdx5/invoice-barcodes.pdf?dl=1",
					:order/package-download 		"https://www.dropbox.com/s/ugq6zxuer7kmrl1/package-barcodes.zip?dl=1",
					:order/barcodes  				 [111111 222222 333333 444444 555555]
					:order/owner-email            	 "bruce.wayne@batcave.com",
					:order/customer-address-street	 "42 Wayne Street, Gotham",
					:order/quantity              	  6,
					:order/product-code          	  "Codigo de barras",
					:order/amount                	  "60.00M",
					:order/customer-name          	 "Bruce Wayne",
					:order/customer-phone         	 "0721234567",
					:order/customer-address-zip   	 "71939540",
					:order/owner-name             	 "Wayne Enterprises",
					:order/address-state          	 "DF",
					:order/customer-address-city  	 "Brasilia",
					:order/customer-tax-id       	  "95414332191"}
	
				{:order/type					 :order.type/barcodes,
				:order/reference         	      "383204287007",
				:order/date            		  	 "3/10/2018",
				:order/status					"canceled",
				:order/invoice-download			"https://www.dropbox.com/s/v6lgrhheu8rqdx5/invoice-barcodes.pdf?dl=1",
				:order/package-download 		"https://www.dropbox.com/s/ugq6zxuer7kmrl1/package-barcodes.zip?dl=1",
				:order/barcodes  				 [111111 222222 333333]
				:order/owner-email            	 "bruce.wayne@batcave.com",
				:order/customer-address-street	 "42 Wayne Street, Gotham",
				:order/quantity              	  3,
				:order/product-code          	  "Codigo de barras",
				:order/amount                	  "30.00M",
				:order/customer-name          	 "Bruce Wayne",
				:order/customer-phone         	 "0721234567",
				:order/customer-address-zip   	 "71939540",
				:order/owner-name             	 "Wayne Enterprises",
				:order/address-state          	 "DF",
				:order/customer-address-city  	 "Brasilia",
				:order/customer-tax-id       	  "95414332191"}

				{:order/type					 :order.type/barcodes,
				:order/reference         	      "483204287007",
				:order/date            		  	 "4/10/2018",
				:order/status					"canceled",
				:order/invoice-download			"https://www.dropbox.com/s/v6lgrhheu8rqdx5/invoice-barcodes.pdf?dl=1",
				:order/package-download 		"https://www.dropbox.com/s/ugq6zxuer7kmrl1/package-barcodes.zip?dl=1",
				:order/barcodes  				 [111111 222222 333333 444444]
				:order/owner-email            	 "bruce.wayne@batcave.com",
				:order/customer-address-street	 "42 Wayne Street, Gotham",
				:order/quantity              	  4,
				:order/product-code          	  "Codigo de barras",
				:order/amount                	  "40.00M",
				:order/customer-name          	 "Bruce Wayne",
				:order/customer-phone         	 "0721234567",
				:order/customer-address-zip   	 "71939540",
				:order/owner-name             	 "Wayne Enterprises",
				:order/address-state          	 "DF",
				:order/customer-address-city  	 "Brasilia",
				:order/customer-tax-id       	  "95414332191"}

				{:order/type					 :order.type/barcodes,
				:order/reference         	      "583204287007",
				:order/date            		  	 "5/10/2018",
				:order/status					"completed",
				:order/invoice-download			"https://www.dropbox.com/s/v6lgrhheu8rqdx5/invoice-barcodes.pdf?dl=1",
				:order/package-download 		"https://www.dropbox.com/s/ugq6zxuer7kmrl1/package-barcodes.zip?dl=1",
				:order/barcodes  				 [111111 222222 333333 444444 555555]
				:order/owner-email            	 "bruce.wayne@batcave.com",
				:order/customer-address-street	 "42 Wayne Street, Gotham",
				:order/quantity              	  5,
				:order/product-code          	  "Codigo de barras",
				:order/amount                	  "50.00M",
				:order/customer-name          	 "Bruce Wayne",
				:order/customer-phone         	 "0721234567",
				:order/customer-address-zip   	 "71939540",
				:order/owner-name             	 "Wayne Enterprises",
				:order/address-state          	 "DF",
				:order/customer-address-city  	 "Brasilia",
				:order/customer-tax-id       	  "95414332191"}

	]}]`
